apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: receiptify

resources:
- namespace.yaml
- backend
- frontend

commonLabels:
  app.kubernetes.io/name: receiptify
  app.kubernetes.io/managed-by: argocd
