apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: receiptify-frontend
  labels:
    app: receiptify-frontend
    tier: frontend
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - receiptify.example.com
    secretName: receiptify-tls
  rules:
  - host: receiptify.example.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: receiptify-backend
            port:
              number: 5000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: receiptify-frontend
            port:
              number: 80
