apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: receiptify

commonLabels:
  app.kubernetes.io/name: receiptify
  app.kubernetes.io/component: frontend

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

images:
- name: ghcr.io/YOUR_USERNAME/receiptify/frontend
  newTag: latest
