apiVersion: v1
kind: Service
metadata:
  name: receiptify-frontend
  labels:
    app: receiptify-frontend
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: receiptify-frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
